@enigma.Server_HostAddress = http://localhost:5264

GET {{enigma.Server_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{enigma.Server_HostAddress}}/todoitems
Accept: application/json

###

POST {{enigma.Server_HostAddress}}/todoitems
Content-Type: application/json

{
  "title": "Buy milk",
  "isDone": false
}

###
